import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.js
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Space Project</title>
      </head>
      <body style={{ margin: 0, fontFamily: 'Arial, sans-serif', backgroundColor: '#000' }}>
        <header style={{ padding: '1rem', backgroundColor: '#001a33', color: '#fff' }}>
          <h2>Space Exploration Project</h2>
        </header>
        <main>{children}</main>
        <footer style={{ padding: '1rem', backgroundColor: '#001a33', color: '#fff', textAlign: 'center' }}>
          <p>© 2024 Space Exploration Project</p>
        </footer>
      </body>
    </html>
  );
}

